### ISSUE TITLE
[Errno 2] No such file or directory: 'G:\\controlGIF\\configs\\inference\\inference-v2.yaml'

### ISSUE THREAD

**Issue by isamu2025** [crystallee-ai/controlGIF#1]
(controlgif) G:\controlGIF>python app.py
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 1.13.1+cu117 with CUDA 1107 (you have 1.13.1+cpu)
    Python  3.10.9 (you have 3.10.13)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
G:\controlGIF\animatediff\pipelines\pipeline_animation.py:19: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
Traceback (most recent call last):
  File "G:\controlGIF\app.py", line 249, in <module>
    controller = AnimateController()
  File "G:\controlGIF\app.py", line 78, in __init__
    self.inference_config      = OmegaConf.load("configs/inference/inference-v2.yaml")
  File "d:\tools\anaconda3\envs\controlgif\lib\site-packages\omegaconf\omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\controlGIF\\configs\\inference\\inference-v2.yaml'

**Comment by crystallee-ai** [comment]
I just already push the config file
