### ISSUE TITLE
Model paths confirmation

### ISSUE THREAD

**Issue by SoftologyPro** [crystallee-ai/controlGIF#3]
I have it installed under D:\Tests\controlGIF\

Is this the correct directory structure under checkpoints?

```
checkpoints
├───basemodels
├───controlnet
│   └───animatediff_controlnet
├───stable-diffusion-v1-5
│   ├───feature_extractor
│   ├───safety_checker
│   ├───scheduler
│   ├───text_encoder
│   ├───tokenizer
│   ├───unet
│   └───vae
└───unet_temporal
    └───animatediff_controlnet
```

I downloaded all the models into the above directories.  python app.py starts and the UI opens.

In the first Pretrained Model Path dropdown I select
`D:\Tests\controlGIF\checkpoints\stable-diffusion-v1-5\`
and it seems to load OK.  Command line shows
```
### Temporal Module Parameters: 453.20928 M
update stable diffusion done!
```

Next dropdown Select Motion Module.  If I click anywhere in that area or try and drop down the list I get error and the command line shows
`TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'`
If I click the reload button next to the dropdown, the error goes away, but when I click the dropdown arrow nothing shows up?

If I click the Select base Dreambooth model dropdown nothing happens.  Then a second time I get the error.
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
If I click the reload button next to that the error goes away, but nothing in the dropdown list.

**Comment by crystallee-ai** [comment]
Thank you for your feedback! the directory structure is :
checkpoints
├───basemodels
├───controlnet
│   └───controlnet_checkpoint.ckpt
├───stable-diffusion-v1-5
│   ├───feature_extractor
│   ├───safety_checker
│   ├───scheduler
│   ├───text_encoder
│   ├───tokenizer
│   ├───unet
│   └───vae
└───unet_temporal
    └───motion_checkpoint_less_motion.ckpt
    └───motion_checkpoint_more_motion.ckpt
 Then you can choose model in the webui.

**Comment by SoftologyPro** [comment]
OK, so my checkpoints are in the right directroies then,
What about the error when a model is selected or nothing in the dropdowns?
Am I supposed to select
`D:\Tests\controlGIF\checkpoints\stable-diffusion-v1-5\`
in the first dropdown?

**Comment by crystallee-ai** [comment]
Yes, you can choose this dir:
<img width="602" alt="3" src="https://github.com/crystallee-ai/controlGIF/assets/120543703/a61b8587-e4e3-41d1-a387-8ce86c0c737a">

**Comment by SoftologyPro** [comment]
OK, I select that directory and it loads.
Then when I click the "Select motion module" dropdown, the first time it shows nothing in the dropdown list, then the second click it shows error and the commandline shows...

```
Traceback (most recent call last):
  File "D:\Tests\controlGIF\voc_controlgif\lib\site-packages\gradio\routes.py", line 508, in predict
    output = await route_utils.call_process_api(
  File "D:\Tests\controlGIF\voc_controlgif\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Tests\controlGIF\voc_controlgif\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "D:\Tests\controlGIF\voc_controlgif\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Tests\controlGIF\voc_controlgif\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Tests\controlGIF\voc_controlgif\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Tests\controlGIF\voc_controlgif\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Tests\controlGIF\voc_controlgif\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "D:\Tests\controlGIF\app.py", line 109, in update_motion_module
    motion_module_dropdown = os.path.join(self.motion_module_dir, motion_module_dropdown)
  File "D:\Python\lib\ntpath.py", line 143, in join
    genericpath._check_arg_types('join', path, *paths)
  File "D:\Python\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

**Comment by crystallee-ai** [comment]
You can reload the webui, this error usually comes from you selecting nothing.

**Comment by SoftologyPro** [comment]
Reload how?

If I hit the browser reload button the page reloads and I have to select the "pretrained base model" again.  After that, the same error with the "Select motion module" dropdown.

If I close the web page completely and then open http://127.0.0.1:7860/ again, same errors.

"It comes from selecting nothing" makes sense, because there is nothing to select in the dropdown.

**Comment by SoftologyPro** [comment]
I worked out the "Select motion model" issue.  Caused by me.
I used git clone to download https://huggingface.co/crishhh/animatediff_controlnet so it put the models under a `unet_temporal\animatediff_controlnet` 
folder.
Once I downloaded the models individually to the right directories it works fine.

**Comment by crishhh1998** [comment]
Sorry for causing misunderstanding, I will update the readme as soon as possible

**Comment by JPW0080** [comment]
Also, base Dreambooth model needs to be .safetensors or the selection option remains empty...

**Comment by yangwang201911** [comment]
@crystallee-ai the link to `stable-diffusion-v1-5` is invalid now. could you help provide the link of this model?

**Comment by crystallee-ai** [comment]
Maybe you can find it in modelscope: https://modelscope.cn/models/AI-ModelScope/stable-diffusion-v1-5

**Comment by crystallee-ai** [comment]
> @crystallee-ai the link to `stable-diffusion-v1-5` is invalid now. could you help provide the link of this model?
Maybe you can find it in modelscope: https://modelscope.cn/models/AI-ModelScope/stable-diffusion-v1-5

**Comment by yangwang201911** [comment]
> > @crystallee-ai the link to `stable-diffusion-v1-5` is invalid now. could you help provide the link of this model?
> > Maybe you can find it in modelscope: https://modelscope.cn/models/AI-ModelScope/stable-diffusion-v1-5

got it. thanks a lot.  I would greatly appreciate it if you could provide the prompt for the demo picture in the homepage of this repo?
